# SegFormer default configuration for nnUNet integration

model:
  model_path: "nnunetv2.model.model_segformer_0"
  backbone: "dinov3"
  backbone_size: "large"
  checkpoint_path: ""
  decoder:
    hidden_size: 256

lora:
  enabled: false
  r: 8
  lora_alpha: 16
  target_modules: ["qkv"]
  lora_dropout: 0.05

train:
  initial_lr: 0.001
  weight_decay: 0.00003
  gradient_clip: 12.0
  num_epochs: 500
  # num_iterations_per_epoch: 10
  num_val_iterations_per_epoch: 2
