# Config for Mask2Former training

bs: 2
n_gpus: 1
metric_to_save: 'mIoU'
model_dtype: BFLOAT16
scheduler:
  total_iter: 40000
  type: 'WarmupOneCycleLR'
  constructor_kwargs:
    warmup_iters: 1500
    warmup_ratio: 1e-6
    final_div_factor: .inf
    pct_start: 0
    anneal_strategy: 'cos'
    use_beta1: False
    update_momentum: False
optimizer:
  lr: 1e-4
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.05
  gradient_clip: 0.01
datasets:
  root: "/data_B/xujialiu/projects/dinov3/semantic_retina_vessel_segmentation"
  train: "ADE20K:split=TRAIN"
  val: "ADE20K:split=VAL"
decoder_head:
  type: "m2f"
  backbone_out_layers: FOUR_EVEN_INTERVALS
  num_classes: 4
  hidden_dim: 2048
m2f_train:
  num_points: 12544
  oversample_ratio: 3.0
  importance_sample_ratio: 0.75
  mask_coefficient: 5.0
  dice_coefficient: 5.0
  class_coefficient: 2.0
  no_object_coefficient: 0.1
transforms:
  train:
    img_size: 448
    random_img_size_ratio_range: [0.5, 2.0]
    crop_size: [448, 448]
    flip_prob: 0.5
  eval:
    img_size: 896
    tta_ratios: [1.0,1.1]
eval:
  compute_metric_per_image: False
  reduce_zero_label: False
  mode: "slide"
  crop_size: 448
  stride: 596
  eval_interval: 100
  use_tta: False
  num_visualizations: 3
